Final group capstone : Car reservation
Pamphilemkp/car-reservation pull request #18
Opened 2023-01-05 23:50 UTC by Pamphilemkp

We have implemented 80% of the tasks from 3 partners and two remaining parts are still not yet implemented, according to the Kanban board the 3 completed tasks are: the home page, the detail page the proper authentication for login and sign-in, without the remaining parts we were not able to create a live demo for the project, please kindly refer to the Microverse requirements when the unexpected happens.

Unexpected issues

In the case of some unexpected issues that can cause delay, you might need to compromise some features. Remember that if you implement at least 80% of the required features and provide a good explanation for the fact that some requirements are not met, your project will be accepted.

2023-01-06 04:11 UTC, Meltrust requested changes
_note:  This project is lacking the API documentation and reservations functionality.  The students explained their reasons in the PR description._

Hi @Pamphilemkp,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  API is working well✔️




#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._

_I strongly recommend you take them into account as they can improve your final evaluation._





Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-01-06 04:11 UTC, Meltrust commented on README.md
> +bundle exec rspec /spec
- [ ]  You are using Rspec, but the "test" folder still exists, which is used by another test framework. Kindly consider deleting that folder if you are not using it. 👍
- [ ] The command shown in your instructions for the tests is not working:
![image](https://user-images.githubusercontent.com/57421823/210927804-bb3d44e3-a1c3-4c69-9163-5f00bc85c039.png)

This one works:  `rspec ./spec'

Result:

![image](https://user-images.githubusercontent.com/57421823/210927888-015919e1-96b3-421a-a978-25860588dfe5.png)

- [ ] As shown above, your backend app has no tests.  Kindly add some in order to ensure your app's integrity. 👍

2023-01-06 04:11 UTC, Meltrust commented on .gitignore
>  /config/master.key
- [ ] You are not pushing to the repo de master key.  I had to create my own to run the project, however since this project needs to be reviewed and it's meant for educational purposes in this case is safe to push the key to the repo, so we can review the project.  Therefore, kindly either remove the `master.key` from `.gitignore` or please include specific instructions and the steps about how to properly run your project without a master key present. 👍

2023-01-06 04:32 UTC, Meltrust requested changes
# Frontend review comments

Hi @Pamphilemkp,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Beautiful frontend ✔️ 



#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._

_I strongly recommend you take them into account as they can improve your final evaluation._





Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-01-06 04:32 UTC, Meltrust commented on README.md
> +<a name="readme-top"></a>
_note:  I couldn't find an open PR, in the frontend project or a link to it to do a proper review.  I'll include my comments regarding that project here._

# Frontend comments

- [ ]  On the "License" section of your readme, the link is broken because it points to a file that does not exist in your project.

## Tips and extra help

Go [here](https://github.com/microverseinc/readme-template), grab the `MIT.md` file from that repo, paste it on the root of your project, and link to it in the "License" section of your readme.

That way, your app will be well documented 💪

- [ ] Your frontend project looks good.  Let's show it off with a screenshot on your readme. 👍 
- [ ] The default test `App.test.js` that comes with React still exists in the project, and it's obviously failing.  Kindly remove it.  That way, all the tests will pass.
- [ ]  Please, kindly refactor this and all other functions in your project to ES6 arrow functions, so your code complies with the latest standards.

Refactoring is easy:

```javascript
const App = () => {
  // ...
}
```
![image](https://user-images.githubusercontent.com/57421823/210929445-4c77cde0-4206-49a8-84cb-eece4c358efd.png)



## Explanation

The `function` keyword has been soft deprecated in almost all the software industry in favor of ES6 arrow functions. This means, almost nobody uses it anymore, so much that it's considered non-best practice.

You can do a search in Vscode for the "function" word, and correct as needed.  Shouldn't take you more than 5-10 min so don't worry.

- [ ] In the Hompaje.js component, there is a big issue when the app consumes the API for the list of cars:

![image](https://user-images.githubusercontent.com/57421823/210929715-330b3709-7e74-4c96-a186-9af7d49b9e70.png)

It never stops!! My PC almost crashed I had to pause it.

## Explanation

This is the problem:

![image](https://user-images.githubusercontent.com/57421823/210929829-a161d800-0b18-4d0f-a9b3-e8fc455e0639.png)

You are using the useEffect hook with no arguments.  Therefore, it is firing the dispatch without limit and without stop.

## Tips and extra help

This is the solution:

![image](https://user-images.githubusercontent.com/57421823/210930022-8c1f68b1-fd66-47da-a431-f108d9e637a9.png)

If the last argument is an empty array, the useEffect hook will trigger **once**, only on the first render.  

Kindly correct this bug so your app works as intended.  Also, you will prevent your API to receive requests thousands of times. 💪 

- [ ] Kindly remove the old commented code present in `Register.js` and `getauthuser.js`.

2023-01-06 06:44 UTC, Pamphilemkp commented
There some are parts which were not implemented such as the reservation functionality and add items, the partners who were assigned these tasks didn't not finish their parts, which even made it difficult to generate the api documentation, please kindly take that into consideration when reviewing this work

## Microverse: 

Unexpected issues

In the case of some unexpected issues that can cause delay, you might need to compromise some features. Remember that if you implement at least 80% of the required features and provide a good explanation for the fact that some requirements are not met, your project will be accepted.

2023-01-06 10:55 UTC, Meltrust requested changes
_note:  The docs and the reservations functionality are missing.  The students have included an explanation for this in the PR description._

_note to student: I am taking your note into consideration and **only** reviewing the work/features that are finished.  My goal is to ensure success in your final evaluation by making suggestions to polish/correct the work that is present.  Of course, since this is a special review, you can choose to ignore my suggestions and present the work directly to the final evaluator._

Hi @Pamphilemkp,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Rspec tests have been added✔️
-  master.key instructions have been added ✔️ 

- Frontend screenshot has been added ✔️ 
- Frontend react default test has been removed ✔️ 




#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._

_I strongly recommend you take them into account as they can improve your final evaluation._





Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-01-06 10:55 UTC, Meltrust commented on README.md
> +rspec ./spec
- [ ] Good job updating this command and adding tests.  However, the "test" folder which is used by another test framework still exists.  Please remove it if not using it.

If you are indeed using that folder, the command in your instructions `sh
  bin/rails test test/models/article_test.rb` provides no output:

![image](https://user-images.githubusercontent.com/57421823/210988927-cbec28c3-8428-47f6-bf70-767c4490312e.png)

If I remove the `sh` from the command:

![image](https://user-images.githubusercontent.com/57421823/210988205-6dbbd915-d27d-43b0-887b-7b26172b877c.png)



If there are special setup procedures to run this test, kindly include them in your readme otherwise I'd suggest removing the `test` folder because you already implemented rspec tests.

2023-01-06 10:55 UTC, Meltrust commented on README.md
> +<div align="center">
# Frontend comments

- [ ] The license link in your readme is still broken.  Kindly fix it:

Go [here](https://github.com/microverseinc/readme-template), grab the `MIT.md` file from that repo, paste it on the root of your project, and link to it in the "License" section of your readme.

- [ ] The `App` and `Detailspage` components are still using the `function` keyword.  Kindly refactor to ES6 arrow function.

- [ ] The commented code on `Register.js` and `getauthuser.js` files has not been removed.

- [ ] Most importantly, in `HomePage.js` `useEffect` issue has not been corrected.  Because of this, the app is making requests to the API multiple times without control.  Kindly just add a second argument to your `useEffect` hook: `[ ]`.  That way, the app will fetch the cars just once, and not thousands of times.

2023-01-07 17:34 UTC, Meltrust approved these changes
Hi @Pamphilemkp,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- License links have been fixed✔️
- master.key instructions have been added to readme ✔️  
- The test folder has been removed ✔️
- Tests have been implemented, and corrected ✔️
- Documentation for the API has been added! ✔️

- In the frontend, screenshots have been added. ✔️
- The React example test has been removed ✔️
- The `App` component has been refactored to ES6. ✔️
- Commented code has been removed ✔️
- The frontend is beautiful. ✔️
- Most importantly, the API call loop on Homepage.js has been fixed, and it works! ✔️
- Excellent job, congratulations 👍 ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] OPTIONAL: May I suggest you refactor the `DetailsPage` component in `DetailsPage.js` to ES6? 

![image](https://user-images.githubusercontent.com/57421823/211163075-890838db-cbda-4e24-8244-16416fad2a32.png)

As a bonus, I already did it for you:


```JAVASCRIPT
const DetailsPage = () => {
  // Get the userId param from the URL.
  let { id } = useParams();
  id = parseInt(id, 10);
  const cars = useSelector((state) => state.CarReducers);
  const dispatch = useDispatch();

  if (cars.length === 0) {
    dispatch(FetchCar());
  }

  // find the product with the id
  const car = cars.find((product) => product.id === id);

  return (
    <div className="app shadow-lg rounded">
      <div className="details" key={car.id}>
        <div className="img-div">
          <img className="w-100" src={car.photo} alt={car.name} />
        </div>
        <div className="box">
          <header className="d-flex justify-content-end flex-column align-items-end">
            <h2>{car.name}</h2>
            <span>{car.brand}</span>
          </header>
          <p className="px-3">{car.description}</p>
          <div className=" booking-div d-flex justify-content-between align-items-center p-2">
            <span>Booking fee:</span>
            <span>
              $
              {car.price}
            </span>
          </div>
          <div className="duration-div d-flex justify-content-between align-items-center p-2">
            <span>Duration:</span>
            <span>1 month</span>
          </div>
          <div className="color-div d-flex justify-content-end py-3">
            <img src={color} alt="" />
          </div>
          <div className="color-div d-flex justify-content-end py-3">
            <button
              type="button"
              className="btn reserve-btn d-flex justify-content-between align-items-center"
            >
              <i className="fa fa-cog text-white" aria-hidden="true" />
              <span className="text-white">Reserve</span>
              <span className="chevron-div">
                <i className="fas fa-chevron-right text-white" />
              </span>
            </button>
          </div>
        </div>
        <Link to="/">
          <div className="back-chevron-div">
            <i className="fas fa-chevron-left text-white" />
          </div>
        </Link>
      </div>
    </div>
  );
};

```



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-09 11:20 UTC, merged